# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user_submit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='belt_exam.User'),
        ),
    ]
